namespace DiskMap.Core;

/// <summary>How freely an item can go to the Recycle Bin.</summary>
public enum CleanupAdvice
{
    /// <summary>Regenerable or plainly user-owned — no special warning.</summary>
    Fine,
    /// <summary>Worth a look first (re-downloadable, but costs time or bandwidth).</summary>
    Review,
    /// <summary>Recycling breaks something (a WSL distro, a VM, an installed app) — warn before staging.</summary>
    Warn,
    /// <summary>Operating-system state — never offered for cleanup.</summary>
    Never,
}

/// <summary>A preconfigured storage category — what a typical laptop's bytes are.</summary>
public sealed record StorageClass(string Id, string Title, string ColorHex, string Blurb);

/// <summary>A path's category plus what removing it means.</summary>
public sealed record StorageVerdict(
    StorageClass Class,
    CleanupAdvice Advice,
    /// <summary>Why removing it is risky (Warn/Never) or what to check (Review).</summary>
    string? Note = null,
    /// <summary>The right way to reclaim the space instead of the Recycle Bin, when there is one.</summary>
    string? Instead = null);

/// <summary>
/// Path-rule classifier for a whole drive or home folder: WSL and Docker
/// disks, VMs, AI models, dev projects and toolchains, browsers, games,
/// cloud folders, personal folders… everything a general laptop holds,
/// with whatever no rule claims left as Other.
///
/// Rules match the end of a folder's path (segment by segment, `*` as a
/// trailing wildcard), optionally anchored at a depth from the drive root.
/// A <i>claim</i> rule takes the whole subtree; an <i>area</i> rule only
/// sets the default for the subtree and keeps descending, so
/// Documents\codes\app\node_modules is still Dependencies while the rest
/// of Documents\codes is Code &amp; projects. Every byte lands in exactly
/// one class — <see cref="Rollup"/> sums to the root's total.
/// </summary>
public static class StorageClassifier
{
    public static readonly StorageClass System = new("system", "Windows & system", "#8A94A6",
        "Windows, recovery and memory files — managed by Windows.");
    public static readonly StorageClass Apps = new("apps", "Installed apps", "#6E8EF0",
        "Program Files and per-user app installs.");
    public static readonly StorageClass VirtualDisks = new("vms", "WSL, Docker & VMs", "#E0784A",
        "Linux distros, container disks, emulators and virtual machines.");
    public static readonly StorageClass Projects = new("projects", "Code & projects", "#3B82C4",
        "Your source folders and repositories.");
    public static readonly StorageClass Dependencies = new("deps", "Dependencies & builds", "#2FA37A",
        "node_modules, virtualenvs, build output — regenerated by your tools.");
    public static readonly StorageClass DevTools = new("devtools", "Dev tools & SDKs", "#5B6FD6",
        "Toolchains, SDKs, editors and their per-user data.");
    public static readonly StorageClass PackageCaches = new("pkgcache", "Package caches", "#38B2AC",
        "npm, pip, NuGet, Gradle… download caches — refilled on demand.");
    public static readonly StorageClass AiModels = new("ai", "AI models", "#9F5BD6",
        "Model weights and hub caches — usually re-downloadable.");
    public static readonly StorageClass Browsers = new("browsers", "Browser data", "#D6A13A",
        "Browser profiles: history, logins, extensions, caches.");
    public static readonly StorageClass Games = new("games", "Games", "#D65B8F",
        "Game libraries and saves.");
    public static readonly StorageClass Cloud = new("cloud", "Cloud sync folders", "#4AA8D8",
        "OneDrive, Google Drive, Dropbox, iCloud.");
    public static readonly StorageClass Media = new("media", "Photos, videos & music", "#E06C9F",
        "Pictures, Videos and Music folders.");
    public static readonly StorageClass Documents = new("documents", "Documents & desktop", "#7A9A5B",
        "Documents and Desktop.");
    public static readonly StorageClass Downloads = new("downloads", "Downloads", "#C98A3D",
        "The Downloads folder.");
    public static readonly StorageClass Installers = new("installers", "Installers & disk images", "#B07A4E",
        "ISOs, MSIs and other installers — usually re-downloadable.");
    public static readonly StorageClass Caches = new("caches", "Caches & temp", "#9AA35B",
        "Temp folders, crash dumps and app caches.");
    public static readonly StorageClass AppData = new("appdata", "App data", "#8C7AB8",
        "Settings and data apps keep in AppData and ProgramData.");
    public static readonly StorageClass Other = new("other", "Other", "#9AA3AF",
        "Everything no rule recognizes.");

    /// <summary>Display order (Other last).</summary>
    public static readonly IReadOnlyList<StorageClass> All =
    [
        Projects, Dependencies, DevTools, PackageCaches, VirtualDisks, AiModels,
        Documents, Media, Downloads, Installers, Cloud, Games, Browsers,
        Apps, AppData, Caches, System, Other,
    ];

    public static StorageClass ById(string id) => All.FirstOrDefault(c => c.Id == id) ?? Other;

    /// <summary>
    /// The Recycle Bin and restore-point store: what's in there was already
    /// thrown away or belongs to Windows — never a finding (a node_modules
    /// sitting in the bin is not developer storage to clean).
    /// </summary>
    public static bool IsSystemHolding(string path) =>
        path.Contains(@"\$Recycle.Bin", StringComparison.OrdinalIgnoreCase)
        || path.Contains(@"\System Volume Information", StringComparison.OrdinalIgnoreCase);

    /// <summary>True for the classes a developer owns — the Developer Storage family.</summary>
    public static bool IsDeveloper(StorageClass c) =>
        c == Projects || c == Dependencies || c == DevTools || c == PackageCaches || c == VirtualDisks || c == AiModels;

    // ---- Rules ----

    private const string WslNote =
        "This is a whole Linux distribution (WSL). Recycling it deletes the distro and every file inside it.";
    private const string WslInstead =
        "Remove a distro with `wsl --unregister <name>`, or shrink it: `wsl --manage <name> --set-sparse true`.";
    private const string DockerNote =
        "Docker Desktop's disk — holds every image, container and volume. Recycling it wipes Docker's data.";
    private const string DockerInstead =
        "Run `docker system prune -a` (and `docker volume prune`), or Docker Desktop → Troubleshoot → Clean / Purge data.";
    private const string VmNote = "A virtual machine disk — recycling it deletes that machine.";
    private const string AvdNote = "Android emulator state — recycling it deletes the emulator and its data.";
    private const string AvdInstead = "Delete emulators from Android Studio's Device Manager.";
    private const string AppNote = "Part of an installed app — removing files breaks it.";
    private const string AppInstead = "Uninstall from Settings → Apps → Installed apps.";
    private const string BrowserNote = "A browser profile: history, saved logins, extensions and settings live here.";
    private const string BrowserInstead = "Clear cached data from the browser's own settings instead.";
    private const string GitNote = "Repository history — anything not pushed is lost with it.";
    private const string GameNote = "An installed game library.";
    private const string GameInstead = "Uninstall games from their launcher (Steam, Epic, Xbox app).";
    private const string SystemNote = "Managed by Windows.";
    private const string SystemInstead = "Use Settings → System → Storage → Temporary files.";
    private const string RedownloadNote = "Re-downloadable, but it costs time and bandwidth to get back.";

    private sealed record Rule(
        string[] Pattern, StorageClass Class, bool Claim,
        CleanupAdvice Advice = CleanupAdvice.Fine, string? Note = null, string? Instead = null,
        int AnchorDepth = -1);

    private static Rule Claim(string pattern, StorageClass c, CleanupAdvice a = CleanupAdvice.Fine,
        string? note = null, string? instead = null, int depth = -1) =>
        new(Split(pattern), c, true, a, note, instead, depth);

    private static Rule Area(string pattern, StorageClass c, CleanupAdvice a = CleanupAdvice.Fine,
        string? note = null, string? instead = null, int depth = -1) =>
        new(Split(pattern), c, false, a, note, instead, depth);

    private static string[] Split(string pattern) =>
        pattern.ToLowerInvariant().Split('/', StringSplitOptions.RemoveEmptyEntries);

    /// <summary>
    /// Folder rules, first match wins — specific before general. Depth 1
    /// = a folder directly under the drive root (C:\Windows); `?` matches
    /// any one segment (the user name in Users\?\…).
    /// </summary>
    private static readonly Rule[] FolderRules =
    [
        // Drive root.
        Claim("windows", System, CleanupAdvice.Never, SystemNote, SystemInstead, depth: 1),
        Claim("windows.old", System, CleanupAdvice.Review, "A previous Windows installation.",
            "Remove it with Settings → System → Storage → Temporary files → Previous Windows installation.", depth: 1),
        Claim("$recycle.bin", System, CleanupAdvice.Never, "The Recycle Bin itself.", "Empty the Recycle Bin.", depth: 1),
        Claim("system volume information", System, CleanupAdvice.Never, "Restore points and the change journal.", depth: 1),
        Claim("recovery", System, CleanupAdvice.Never, SystemNote, depth: 1),
        Claim("$windows.~bt", System, CleanupAdvice.Review, "Windows Update staging.", SystemInstead, depth: 1),
        Claim("$windows.~ws", System, CleanupAdvice.Review, "Windows Update staging.", SystemInstead, depth: 1),
        Claim("$winreagent", System, CleanupAdvice.Never, SystemNote, depth: 1),
        Claim("perflogs", System, CleanupAdvice.Review, depth: 1),
        Claim("boot", System, CleanupAdvice.Never, SystemNote, depth: 1),
        Claim("programdata/microsoft/windows/hyper-v", VirtualDisks, CleanupAdvice.Warn, VmNote, depth: 1),
        Area("programdata/microsoft", System, CleanupAdvice.Never, SystemNote, depth: 1),
        Claim("programdata/package cache", Apps, CleanupAdvice.Warn,
            "Installer cache — apps need it to repair or uninstall.", AppInstead, depth: 1),
        Claim("programdata/docker*", VirtualDisks, CleanupAdvice.Warn, DockerNote, DockerInstead, depth: 1),
        Area("programdata", AppData, depth: 1),
        Claim("program files", Apps, CleanupAdvice.Warn, AppNote, AppInstead, depth: 1),
        Claim("program files (x86)", Apps, CleanupAdvice.Warn, AppNote, AppInstead, depth: 1),
        Claim("xboxgames", Games, CleanupAdvice.Warn, GameNote, GameInstead, depth: 1),
        Claim("riot games", Games, CleanupAdvice.Warn, GameNote, GameInstead, depth: 1),
        Claim("epic games", Games, CleanupAdvice.Warn, GameNote, GameInstead, depth: 1),
        Claim("steamlibrary", Games, CleanupAdvice.Warn, GameNote, GameInstead, depth: 1),
        Claim("msys64", DevTools, CleanupAdvice.Review, depth: 1),
        Claim("cygwin*", DevTools, CleanupAdvice.Review, depth: 1),
        Claim("mingw*", DevTools, CleanupAdvice.Review, depth: 1),
        Claim("flutter", DevTools, CleanupAdvice.Review, depth: 1),
        Claim("python*", DevTools, CleanupAdvice.Review, depth: 1),
        Claim("xampp", DevTools, CleanupAdvice.Review, depth: 1),
        Claim("laragon", DevTools, CleanupAdvice.Review, depth: 1),
        Area("dev", Projects, depth: 1),
        Area("code", Projects, depth: 1),
        Area("src", Projects, depth: 1),
        Area("repos", Projects, depth: 1),
        Area("projects", Projects, depth: 1),
        Area("workspace*", Projects, depth: 1),

        // Anywhere: regenerable project output. Before the project areas,
        // so they win inside Documents\codes.
        Claim("node_modules", Dependencies),
        Claim("bower_components", Dependencies),
        Claim(".next", Dependencies),
        Claim(".nuxt", Dependencies),
        Claim(".turbo", Dependencies),
        Claim(".parcel-cache", Dependencies),
        Claim(".angular", Dependencies),
        Claim(".svelte-kit", Dependencies),
        Claim(".expo", Dependencies),
        Claim("__pycache__", Dependencies),
        Claim(".pytest_cache", Dependencies),
        Claim(".mypy_cache", Dependencies),
        Claim(".ruff_cache", Dependencies),
        Claim(".tox", Dependencies),
        Claim(".venv", Dependencies),
        Claim("venv", Dependencies),
        Claim(".dart_tool", Dependencies),
        Claim(".terraform", Dependencies),
        Claim("deriveddata", Dependencies),
        Claim(".gradle", PackageCaches),
        Claim(".git", Projects, CleanupAdvice.Warn, GitNote),
        Claim("steamapps", Games, CleanupAdvice.Warn, GameNote, GameInstead),
        Claim("virtualbox vms", VirtualDisks, CleanupAdvice.Warn, VmNote),
        Claim("hyper-v", VirtualDisks, CleanupAdvice.Warn, VmNote),
        Claim("virtual machines", VirtualDisks, CleanupAdvice.Warn, VmNote),

        // Per-user: WSL, Docker, Android, AI caches, toolchains.
        Claim("appdata/local/wsl", VirtualDisks, CleanupAdvice.Warn, WslNote, WslInstead),
        Claim("appdata/local/packages/canonicalgroup*", VirtualDisks, CleanupAdvice.Warn, WslNote, WslInstead),
        Claim("appdata/local/packages/thedebianproject*", VirtualDisks, CleanupAdvice.Warn, WslNote, WslInstead),
        Claim("appdata/local/packages/kalilinux*", VirtualDisks, CleanupAdvice.Warn, WslNote, WslInstead),
        Claim("appdata/local/packages/*suse*", VirtualDisks, CleanupAdvice.Warn, WslNote, WslInstead),
        Claim("appdata/local/packages/whitewatersoftware*", VirtualDisks, CleanupAdvice.Warn, WslNote, WslInstead),
        Claim("appdata/local/docker", VirtualDisks, CleanupAdvice.Warn, DockerNote, DockerInstead),
        Claim("appdata/local/android/sdk", DevTools, CleanupAdvice.Review,
            "The Android SDK — Android Studio re-downloads it, slowly.", "Remove unused system images in Android Studio → SDK Manager."),
        Claim(".android/avd", VirtualDisks, CleanupAdvice.Warn, AvdNote, AvdInstead),
        Area(".android", DevTools, CleanupAdvice.Review),
        Claim(".cache/huggingface", AiModels, CleanupAdvice.Review, RedownloadNote, "Run `huggingface-cli delete-cache`."),
        Claim(".cache/lm-studio", AiModels, CleanupAdvice.Review, RedownloadNote),
        Claim(".cache/torch", AiModels, CleanupAdvice.Review, RedownloadNote),
        Claim(".cache/whisper", AiModels, CleanupAdvice.Review, RedownloadNote),
        Claim(".ollama", AiModels, CleanupAdvice.Review, RedownloadNote, "Run `ollama rm <model>`."),
        Claim(".lmstudio", AiModels, CleanupAdvice.Review, RedownloadNote),
        Claim(".keras", AiModels, CleanupAdvice.Review, RedownloadNote),
        Claim("appdata/local/programs", Apps, CleanupAdvice.Warn, AppNote, AppInstead),
        Claim("appdata/local/microsoft/windowsapps", Apps, CleanupAdvice.Never, AppNote, AppInstead),
        Claim("appdata/local/microsoft/windows", System, CleanupAdvice.Never, SystemNote, SystemInstead),
        Claim("appdata/local/temp", Caches),
        Claim("appdata/local/crashdumps", Caches),
        Claim("appdata/local/npm-cache", PackageCaches),
        Claim("appdata/roaming/npm-cache", PackageCaches),
        Claim("appdata/local/pip", PackageCaches),
        Claim("appdata/local/yarn", PackageCaches),
        Claim("appdata/local/nuget", PackageCaches),
        Claim("appdata/local/pnpm*", PackageCaches),
        Claim("appdata/local/go-build", PackageCaches),
        Claim("appdata/local/ms-playwright", PackageCaches),
        Claim("appdata/local/cypress", PackageCaches),
        Claim("appdata/local/node-gyp", PackageCaches),
        Claim("appdata/local/electron*", PackageCaches),
        Claim("appdata/local/uv", PackageCaches),
        Claim("appdata/roaming/npm", DevTools, CleanupAdvice.Review),
        Claim("appdata/roaming/code", DevTools, CleanupAdvice.Review),
        Claim("appdata/roaming/cursor", DevTools, CleanupAdvice.Review),
        Claim("appdata/local/jetbrains", DevTools, CleanupAdvice.Review),
        Claim("appdata/roaming/jetbrains", DevTools, CleanupAdvice.Review),
        Claim("appdata/local/google/chrome", Browsers, CleanupAdvice.Warn, BrowserNote, BrowserInstead),
        Claim("appdata/local/microsoft/edge", Browsers, CleanupAdvice.Warn, BrowserNote, BrowserInstead),
        Claim("appdata/local/bravesoftware", Browsers, CleanupAdvice.Warn, BrowserNote, BrowserInstead),
        Claim("appdata/local/vivaldi", Browsers, CleanupAdvice.Warn, BrowserNote, BrowserInstead),
        Claim("appdata/local/thebrowsercompany", Browsers, CleanupAdvice.Warn, BrowserNote, BrowserInstead),
        Claim("appdata/roaming/mozilla", Browsers, CleanupAdvice.Warn, BrowserNote, BrowserInstead),
        Claim("appdata/local/mozilla", Browsers, CleanupAdvice.Warn, BrowserNote, BrowserInstead),
        Claim("appdata/roaming/opera software", Browsers, CleanupAdvice.Warn, BrowserNote, BrowserInstead),
        Area("appdata", AppData),

        // Home-folder toolchains (Users\you\.cargo …).
        Claim(".cargo", DevTools, CleanupAdvice.Review),
        Claim(".rustup", DevTools, CleanupAdvice.Review),
        Claim(".m2", PackageCaches),
        Claim(".nuget", PackageCaches),
        Claim(".npm", PackageCaches),
        Claim(".yarn", PackageCaches),
        Claim(".pnpm-store", PackageCaches),
        Claim(".bun", DevTools, CleanupAdvice.Review),
        Claim(".deno", DevTools, CleanupAdvice.Review),
        Claim(".nvm", DevTools, CleanupAdvice.Review),
        Claim(".dotnet", DevTools, CleanupAdvice.Review),
        Claim(".conda", DevTools, CleanupAdvice.Review),
        Claim("anaconda3", DevTools, CleanupAdvice.Review),
        Claim("miniconda3", DevTools, CleanupAdvice.Review),
        Claim(".pyenv", DevTools, CleanupAdvice.Review),
        Claim(".vscode", DevTools, CleanupAdvice.Review),
        Claim(".vscode-server", DevTools, CleanupAdvice.Review),
        Claim(".cursor", DevTools, CleanupAdvice.Review),
        Claim(".codex", DevTools, CleanupAdvice.Review),
        Claim(".docker", DevTools, CleanupAdvice.Review),
        Claim(".platformio", DevTools, CleanupAdvice.Review),
        Claim(".espressif", DevTools, CleanupAdvice.Review),
        Claim(".arduino15", DevTools, CleanupAdvice.Review),
        Claim(".sdkman", DevTools, CleanupAdvice.Review),
        Area(".cache", PackageCaches),
        Claim("users/?/go", DevTools, CleanupAdvice.Review),

        // Personal areas — areas, so dev folders inside still classify.
        Area("users/?/documents/code*", Projects),
        Area("users/?/documents/projects", Projects),
        Area("users/?/documents/repos", Projects),
        Area("users/?/documents/github", Projects),
        Area("users/?/documents/git", Projects),
        Area("users/?/documents/dev", Projects),
        Area("users/?/documents/source", Projects),
        Area("users/?/documents/src", Projects),
        Area("users/?/documents/workspace*", Projects),
        Area("users/?/documents/developer", Projects),
        Area("users/?/documents/visual studio*", Projects),
        Area("users/?/source", Projects),
        Area("users/?/repos", Projects),
        Area("users/?/projects", Projects),
        Area("users/?/code*", Projects),
        Area("users/?/dev", Projects),
        Area("users/?/developer", Projects),
        Area("users/?/workspace*", Projects),
        Area("users/?/github", Projects),
        Area("users/?/git", Projects),
        Area("users/?/saved games", Games),
        Area("users/?/documents/my games", Games),
        Area("users/?/onedrive*", Cloud),
        Area("users/?/google drive", Cloud),
        Area("users/?/dropbox", Cloud),
        Area("users/?/icloud*", Cloud),
        Area("users/?/box", Cloud),
        Area("users/?/documents", Documents),
        Area("users/?/desktop", Documents),
        Area("users/?/downloads", Downloads),
        Area("users/?/pictures", Media),
        Area("users/?/videos", Media),
        Area("users/?/music", Media),
    ];

    /// <summary>File rules by exact name (anywhere) — memory files etc.</summary>
    private static readonly Dictionary<string, StorageVerdict> FileNames =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["pagefile.sys"] = new(System, CleanupAdvice.Never, "Windows virtual memory.",
                "Adjust it under System → Advanced system settings → Performance → Virtual memory."),
            ["hiberfil.sys"] = new(System, CleanupAdvice.Never, "The hibernation file.",
                "Run `powercfg /hibernate off` as administrator to remove it."),
            ["swapfile.sys"] = new(System, CleanupAdvice.Never, "Windows virtual memory."),
            ["dumpstack.log"] = new(System, CleanupAdvice.Never, SystemNote),
            ["dumpstack.log.tmp"] = new(System, CleanupAdvice.Never, SystemNote),
        };

    /// <summary>File rules by extension (anywhere) — win over areas, never over claims.</summary>
    private static readonly Dictionary<string, StorageVerdict> Extensions =
        new(StringComparer.OrdinalIgnoreCase)
        {
            [".vhdx"] = new(VirtualDisks, CleanupAdvice.Warn, VmNote),
            [".vhd"] = new(VirtualDisks, CleanupAdvice.Warn, VmNote),
            [".avhdx"] = new(VirtualDisks, CleanupAdvice.Warn, VmNote),
            [".vmdk"] = new(VirtualDisks, CleanupAdvice.Warn, VmNote),
            [".vdi"] = new(VirtualDisks, CleanupAdvice.Warn, VmNote),
            [".qcow2"] = new(VirtualDisks, CleanupAdvice.Warn, VmNote),
            [".safetensors"] = new(AiModels, CleanupAdvice.Review, RedownloadNote),
            [".gguf"] = new(AiModels, CleanupAdvice.Review, RedownloadNote),
            [".ggml"] = new(AiModels, CleanupAdvice.Review, RedownloadNote),
            [".ckpt"] = new(AiModels, CleanupAdvice.Review, RedownloadNote),
            [".pth"] = new(AiModels, CleanupAdvice.Review, RedownloadNote),
            [".onnx"] = new(AiModels, CleanupAdvice.Review, RedownloadNote),
            [".tflite"] = new(AiModels, CleanupAdvice.Review, RedownloadNote),
            [".iso"] = new(Installers, CleanupAdvice.Fine),
            [".dmg"] = new(Installers, CleanupAdvice.Fine),
            [".msi"] = new(Installers, CleanupAdvice.Fine),
            [".msix"] = new(Installers, CleanupAdvice.Fine),
            [".msixbundle"] = new(Installers, CleanupAdvice.Fine),
            [".appx"] = new(Installers, CleanupAdvice.Fine),
        };

    /// <summary>Lower-cased path segments: "C:\Users\me" → ["c:", "users", "me"].</summary>
    private static string[] Segments(string path) =>
        path.ToLowerInvariant().Split(['\\', '/'], StringSplitOptions.RemoveEmptyEntries);

    /// <summary>
    /// The first folder rule whose pattern ends at <paramref name="count"/>
    /// segments of <paramref name="segs"/>; null when none does.
    /// </summary>
    private static Rule? MatchFolder(string[] segs, int count)
    {
        foreach (var rule in FolderRules)
        {
            int start = count - rule.Pattern.Length;
            if (start < 1) continue;   // never match the drive itself
            if (rule.AnchorDepth >= 0 && start != rule.AnchorDepth) continue;
            bool ok = true;
            for (int k = 0; k < rule.Pattern.Length && ok; k++)
                ok = SegmentMatches(rule.Pattern[k], segs[start + k]);
            if (ok) return rule;
        }
        return null;
    }

    private static bool SegmentMatches(string pattern, string segment)
    {
        if (pattern == "?") return true;
        if (pattern.Length > 2 && pattern[0] == '*' && pattern[^1] == '*')
            return segment.Contains(pattern[1..^1], StringComparison.Ordinal);
        if (pattern[^1] == '*') return segment.StartsWith(pattern[..^1], StringComparison.Ordinal);
        return segment == pattern;
    }

    private static StorageVerdict? FileVerdict(string name)
    {
        if (FileNames.TryGetValue(name, out var byName)) return byName;
        int dot = name.LastIndexOf('.');
        return dot > 0 && Extensions.TryGetValue(name[dot..], out var byExt) ? byExt : null;
    }

    /// <summary>
    /// Classifies one path: the first claim rule along its folders wins;
    /// otherwise a file rule; otherwise the innermost area; otherwise Other.
    /// A claim's advice covers everything inside it (ext4.vhdx under
    /// AppData\Local\wsl is a WSL distro, not just "a disk image").
    /// </summary>
    public static StorageVerdict Classify(string fullPath, bool isDirectory)
    {
        var segs = Segments(fullPath);
        StorageVerdict? area = null;
        int folderCount = isDirectory ? segs.Length : segs.Length - 1;
        for (int count = 2; count <= folderCount; count++)
        {
            if (MatchFolder(segs, count) is not { } rule) continue;
            var verdict = new StorageVerdict(rule.Class, rule.Advice, rule.Note, rule.Instead);
            if (rule.Claim) return verdict;
            area = verdict;
        }
        if (!isDirectory && segs.Length > 0 && FileVerdict(segs[^1]) is { } file) return file;
        return area ?? new StorageVerdict(Other, CleanupAdvice.Fine);
    }

    /// <summary>Bytes per class plus the biggest node each class claimed (for drill-in).</summary>
    public sealed record ClassTotal(StorageClass Class, long Bytes, int? LargestNode);

    /// <summary>
    /// Exclusive rollup of the whole tree into classes: claims take whole
    /// subtrees, files fall to their file rule or the innermost area.
    /// Sums to <c>totals[0]</c>. O(nodes); run it off the UI thread.
    /// </summary>
    public static List<ClassTotal> Rollup(FileTree tree, string rootPath, long[] totals)
    {
        if (tree.Count == 0) return [];
        var bytes = new Dictionary<StorageClass, long>();
        var largest = new Dictionary<StorageClass, (int Node, long Bytes)>();
        void Add(StorageClass c, int node, long size)
        {
            if (size <= 0) return;
            bytes[c] = bytes.GetValueOrDefault(c) + size;
            if (!largest.TryGetValue(c, out var l) || size > l.Bytes) largest[c] = (node, size);
        }

        var rootSegs = Segments(rootPath);
        // The root itself may sit inside a claim or an area (scanning
        // C:\Users\me\AppData\Local\wsl directly).
        StorageClass? rootArea = null;
        for (int count = 2; count <= rootSegs.Length; count++)
        {
            if (MatchFolder(rootSegs, count) is not { } rule) continue;
            if (rule.Claim) return [new ClassTotal(rule.Class, totals[0], 0)];
            rootArea = rule.Class;
        }

        // Depth-first with one shared segment buffer: a frame re-writes its
        // own segment when popped, and everything below it is written by
        // its descendants before any sibling pops — so the buffer always
        // holds the popped folder's full path.
        var segs = new string[rootSegs.Length + 512];
        Array.Copy(rootSegs, segs, rootSegs.Length);
        var stack = new Stack<(int Node, int Depth, StorageClass? Area)>();
        stack.Push((0, rootSegs.Length, rootArea));
        while (stack.TryPop(out var frame))
        {
            if (frame.Node != 0) segs[frame.Depth - 1] = tree.NameOf(frame.Node).ToLowerInvariant();
            for (int c = tree.FirstChild[frame.Node]; c != -1; c = tree.NextSibling[c])
            {
                long size = totals[c];
                if (size <= 0) continue;
                if (!tree.IsDirectory[c])
                {
                    Add(FileVerdict(tree.NameOf(c))?.Class ?? frame.Area ?? Other, c, size);
                    continue;
                }
                if (frame.Depth >= segs.Length) { Add(frame.Area ?? Other, c, size); continue; }
                segs[frame.Depth] = tree.NameOf(c).ToLowerInvariant();
                var rule = MatchFolder(segs, frame.Depth + 1);
                if (rule is { Claim: true }) { Add(rule.Class, c, size); continue; }
                stack.Push((c, frame.Depth + 1, rule?.Class ?? frame.Area));
            }
        }
        return All.Where(bytes.ContainsKey)
            .Select(c => new ClassTotal(c, bytes[c], largest.TryGetValue(c, out var l) ? l.Node : null))
            .OrderByDescending(t => t.Class == Other ? -1 : t.Bytes)
            .ToList();
    }
}
