"""Writes every Dusty drawing the website's scroll story uses, as a TypeScript module.

    python3 export_web.py ~/Downloads/freedisk-website/app/dusty-poses.ts

Full poses use Dusty's 240 grid (paws rest on y=207). Peek poses hide below y=EDGE,
with the paws gripping that edge.
"""
import json, sys

from dusty import EDGE, GRIP, broom, dusty, specks

FULL = {
    "hello": dict(face="dot", mouth_kind="w"),
    "happy": dict(face="happy", mouth_kind="smile", ears=("up", "flopR")),
    "cheer": dict(face="happy", mouth_kind="smile", ears=("up", "upR"), extras=("sparkles",)),
    "proud": dict(face="happy", mouth_kind="w", ears=("up", "upR"), extras=("sparkles",)),
    "focus": dict(face="dot", mouth_kind="o", ears=("perkL", "flopR"), look=(2, 3)),
    "shake": dict(face="closed", mouth_kind="o", ears=("flopL", "flopR")),
    "fly":   dict(face="happy", mouth_kind="smile", ears=("droopL", "droopR")),
}
PEEK = {
    "hello":   dict(face="dot", mouth_kind="w"),
    "curious": dict(face="dot", mouth_kind="o", ears=("perkL", "bentR"), extras=("question",)),
    "happy":   dict(face="happy", mouth_kind="smile", ears=("up", "flopR"), extras=("sparkles",)),
    "sleepy":  dict(face="closed", mouth_kind="tiny", ears=("droopL", "droopR"), extras=("zzz",)),
    "wide":    dict(face="wide", mouth_kind="o", ears=("up", "upR")),
}

def ts(obj): return json.dumps(obj, ensure_ascii=False)

out = ["// Generated by design/mascot/export_web.py in the DiskMap repo. Do not edit by hand.",
       f"export const DUSTY_EDGE = {EDGE};",
       "export const DUSTY_FEET = 207;",
       f"export const DUSTY_GRIP = {ts(list(GRIP))};",
       "export const fullPoses = {"]
for k, kw in FULL.items():
    out.append(f"  {k}: {ts(dusty(uid=f'df-{k}', **kw))},")
out.append("} as const;")
out.append("export const peekPoses = {")
for k, kw in PEEK.items():
    out.append(f"  {k}: {ts(dusty(uid=f'dp-{k}', peek=True, **kw))},")
out.append("} as const;")
out.append(f"export const BROOM = {ts(broom())};")
out.append(f"export const SPECKS = {ts(specks())};")
out.append("export type FullPose = keyof typeof fullPoses;")
out.append("export type PeekPose = keyof typeof peekPoses;")
open(sys.argv[1], "w").write("\n".join(out) + "\n")
print("wrote", sys.argv[1])
