import SwiftUI

// MARK: - Dusty, the freedisk.space mascot
//
// Drawn from DustyArt (generated by design/mascot/export_app.py from the same
// drawings as the website), with one Canvas per Dusty. The art is decoded once,
// the first time a Dusty appears; nothing here runs while no Dusty is on screen.
// Rules (design/mascot): calm and rare, at most one per screen, never on a step
// that removes files, and always optional (Settings ▸ Show Dusty).

enum DustyPose: String, CaseIterable, Sendable {
    case hello, happy, proud, curious, sleepy, oops, focus, shake
    case peekHello, peekCurious, peekHappy
    case smallHello, smallCurious, smallOops, smallDusty

    var isPeek: Bool { rawValue.hasPrefix("peek") }

    /// The drawing's frame in Dusty's 240-unit grid. Peeking poses end at the
    /// ledge their paws grip; the others include the ground shadow.
    var viewBox: CGRect {
        isPeek ? CGRect(x: 0, y: 0, width: 240, height: 184) : CGRect(x: 0, y: 0, width: 240, height: 216)
    }

    /// Height for a given width.
    func height(forWidth width: CGFloat) -> CGFloat { width * viewBox.height / viewBox.width }
}

/// Dusty without his small lives: still poses, no arrivals. For renders that must
/// not depend on timing (the snapshot harness), not for users: they have Reduce Motion.
private struct DustyStillKey: EnvironmentKey { static let defaultValue = false }
extension EnvironmentValues {
    var dustyStill: Bool {
        get { self[DustyStillKey.self] }
        set { self[DustyStillKey.self] = newValue }
    }
}

enum DustyPreference {
    static let key = "ShowDusty"
    static var isOn: Bool { UserDefaults.standard.object(forKey: key) as? Bool ?? true }
}

// MARK: - Art

/// Dusty's drawings, prepared once as Paths.
final class DustyLibrary: @unchecked Sendable {
    static let shared = DustyLibrary()

    enum Role: String { case earL, earR, eye, broom, specks, speck, sparkle, pawL, pawR }
    enum Paint { case color(Color), ink }

    struct Op {
        var path: Path
        var fill: Paint?
        var stroke: Paint?
        var lineWidth: CGFloat
        var roundCap: Bool
        var opacity: Double
        var role: Role?
        var pivot: CGPoint
        var fly: CGVector
        var clips: [Path]
    }

    struct Art {
        var ops: [Op]
    }

    let edge: CGFloat
    let grip: CGPoint
    private(set) var poses: [DustyPose: Art] = [:]
    private(set) var broom = Art(ops: [])
    private(set) var specks = Art(ops: [])

    /// Decodes the art on a background thread, so the first Dusty on screen
    /// never waits for it (about 30 ms, once).
    static func warmUp() {
        Task.detached(priority: .background) { _ = DustyLibrary.shared }
    }

    private init() {
        let root = (try? JSONSerialization.jsonObject(with: Data(DustyArt.json.utf8))) as? [String: Any] ?? [:]
        edge = CGFloat(root["edge"] as? Double ?? 172)
        let grip = root["grip"] as? [Double] ?? [186, 152]
        self.grip = CGPoint(x: grip.first ?? 186, y: grip.last ?? 152)
        let poses = root["poses"] as? [String: [String: Any]] ?? [:]
        for pose in DustyPose.allCases {
            if let raw = poses[pose.rawValue] { self.poses[pose] = Self.art(raw) }
        }
        let overlays = root["overlays"] as? [String: [String: Any]] ?? [:]
        broom = overlays["broom"].map(Self.art) ?? Art(ops: [])
        specks = overlays["specks"].map(Self.art) ?? Art(ops: [])
    }

    private static func art(_ raw: [String: Any]) -> Art {
        // Each clip is one flat segment list (its shapes run one after another).
        let clips = (raw["clips"] as? [[Double]] ?? []).map(path)
        let ops = (raw["ops"] as? [[String: Any]] ?? []).map { o -> Op in
            let p = path(o["d"] as? [Double] ?? [])
            let role = (o["r"] as? String).flatMap(Role.init(rawValue:))
            let pivot = (o["p"] as? [Double]).map { CGPoint(x: $0[0], y: $0[1]) }
                ?? CGPoint(x: p.boundingRect.midX, y: p.boundingRect.midY)
            let fly = (o["fly"] as? [Double]).map { CGVector(dx: $0[0], dy: $0[1]) } ?? .zero
            return Op(path: p, fill: paint(o["f"]), stroke: paint(o["s"]),
                      lineWidth: CGFloat(o["w"] as? Double ?? 1), roundCap: (o["cap"] as? Int) == 1,
                      opacity: o["o"] as? Double ?? 1, role: role, pivot: pivot, fly: fly,
                      clips: (o["c"] as? [Int] ?? []).compactMap { clips.indices.contains($0) ? clips[$0] : nil })
        }
        return Art(ops: ops)
    }

    private static func paint(_ value: Any?) -> Paint? {
        guard let s = value as? String else { return nil }
        if s == "x" { return .ink }
        var hex: UInt64 = 0
        guard Scanner(string: String(s.dropFirst())).scanHexInt64(&hex) else { return nil }
        return .color(Color(.sRGB, red: Double((hex >> 16) & 0xFF) / 255, green: Double((hex >> 8) & 0xFF) / 255,
                            blue: Double(hex & 0xFF) / 255, opacity: 1))
    }

    /// 0 x y move · 1 x y line · 2 cx cy x y quad · 3 c1 c2 p cubic · 4 close.
    private static func path(_ d: [Double]) -> Path {
        var p = Path(), i = 0
        func pt(_ j: Int) -> CGPoint { CGPoint(x: d[j], y: d[j + 1]) }
        while i < d.count {
            let c = Int(d[i]); i += 1
            switch c {
            case 0: guard i + 1 < d.count else { return p }; p.move(to: pt(i)); i += 2
            case 1: guard i + 1 < d.count else { return p }; p.addLine(to: pt(i)); i += 2
            case 2: guard i + 3 < d.count else { return p }; p.addQuadCurve(to: pt(i + 2), control: pt(i)); i += 4
            case 3: guard i + 5 < d.count else { return p }; p.addCurve(to: pt(i + 4), control1: pt(i), control2: pt(i + 2)); i += 6
            default: p.closeSubpath()
            }
        }
        return p
    }
}

// MARK: - Drawing

/// What moves on Dusty, in his 240-unit grid. Animatable, so blinks, glances and
/// ear twitches tween smoothly instead of jumping.
struct DustyLook: Equatable {
    var eye: CGSize = .zero
    var blink: CGFloat = 1
    var earL: Double = 0
    var earR: Double = 0
    /// Broom angle in degrees; nil hides the broom.
    var broom: Double?
    var specks: Double = 0
    var specksFly: Double = 0
    var bob: CGFloat = 0
}

struct DustyCanvas: View, Animatable {
    var pose: DustyPose
    var look: DustyLook
    @Environment(\.colorScheme) private var scheme

    var animatableData: AnimatablePair<AnimatablePair<CGFloat, CGFloat>, AnimatablePair<CGFloat, AnimatablePair<Double, Double>>> {
        get { AnimatablePair(AnimatablePair(look.eye.width, look.eye.height), AnimatablePair(look.blink, AnimatablePair(look.earL, look.earR))) }
        set {
            look.eye = CGSize(width: newValue.first.first, height: newValue.first.second)
            look.blink = newValue.second.first
            look.earL = newValue.second.second.first
            look.earR = newValue.second.second.second
        }
    }

    var body: some View {
        Canvas { context, size in
            let library = DustyLibrary.shared
            guard let art = library.poses[pose] else { return }
            let box = pose.viewBox
            let scale = min(size.width / box.width, size.height / box.height)
            var ctx = context
            ctx.translateBy(x: (size.width - box.width * scale) / 2, y: (size.height - box.height * scale) / 2)
            ctx.scaleBy(x: scale, y: scale)
            if look.bob != 0 { ctx.translateBy(x: 0, y: -look.bob) }
            let ink = scheme == .dark ? Color(red: 233 / 255, green: 230 / 255, blue: 245 / 255) : Color(red: 43 / 255, green: 36 / 255, blue: 64 / 255)
            for op in art.ops { draw(op, in: ctx, ink: ink) }
            if look.specks > 0, !pose.isPeek {
                for op in library.specks.ops { draw(op, in: ctx, ink: ink) }
            }
            if look.broom != nil, !pose.isPeek {
                for op in library.broom.ops { draw(op, in: ctx, ink: ink) }
            }
        }
        .accessibilityHidden(true)
    }

    private func draw(_ op: DustyLibrary.Op, in context: GraphicsContext, ink: Color) {
        var ctx = context
        for clip in op.clips { ctx.clip(to: clip) }
        ctx.opacity = op.opacity
        switch op.role {
        case .earL?, .earR?:
            let angle = op.role == .earL ? look.earL : look.earR
            if angle != 0 { rotate(&ctx, around: op.pivot, degrees: angle) }
        case .eye?:
            ctx.translateBy(x: look.eye.width + op.pivot.x, y: look.eye.height + op.pivot.y)
            ctx.scaleBy(x: 1, y: max(0.04, look.blink))
            ctx.translateBy(x: -op.pivot.x, y: -op.pivot.y)
        case .broom?:
            if let angle = look.broom, angle != 0 { rotate(&ctx, around: op.pivot, degrees: angle) }
        case .speck?:
            ctx.opacity = op.opacity * look.specks * (1 - look.specksFly)
            if look.specksFly > 0 { ctx.translateBy(x: op.fly.dx * look.specksFly, y: op.fly.dy * look.specksFly) }
        default:
            break
        }
        if let fill = op.fill { ctx.fill(op.path, with: .color(color(fill, ink))) }
        if let stroke = op.stroke {
            ctx.stroke(op.path, with: .color(color(stroke, ink)),
                       style: StrokeStyle(lineWidth: op.lineWidth, lineCap: op.roundCap ? .round : .butt, lineJoin: .round))
        }
    }

    private func rotate(_ ctx: inout GraphicsContext, around p: CGPoint, degrees: Double) {
        ctx.translateBy(x: p.x, y: p.y)
        ctx.rotate(by: .degrees(degrees))
        ctx.translateBy(x: -p.x, y: -p.y)
    }

    private func color(_ paint: DustyLibrary.Paint, _ ink: Color) -> Color {
        switch paint {
        case .color(let c): return c
        case .ink: return ink
        }
    }
}

// MARK: - A living Dusty

/// Dusty with his small lives: he blinks, now and then twitches an ear, can look
/// somewhere and can sweep. All of it stops with Reduce Motion, and none of it
/// runs while he is off screen.
struct Dusty: View {
    var pose: DustyPose
    var width: CGFloat
    /// Where to look, -1…1 on each axis (nil = straight ahead).
    var gaze: CGSize?
    var sweeping = false
    /// Holds his broom, still (the About window).
    var broom = false
    var specks: Double = 0
    var specksFly: Double = 0
    var lively = true
    @Environment(\.accessibilityReduceMotion) private var systemReduceMotion
    @Environment(\.dustyStill) private var still
    @State private var blink: CGFloat = 1
    @State private var earL: Double = 0
    @State private var earR: Double = 0

    var body: some View {
        Group {
            if sweeping && !reduceMotion {
                // Only while sweeping (a scan in progress): a gentle 30 fps loop.
                TimelineView(.animation(minimumInterval: 1 / 30)) { timeline in
                    let t = timeline.date.timeIntervalSinceReferenceDate
                    let swing = sin(t * 2 * .pi / 1.15)
                    canvas(broom: swing * 26 - 4, bob: CGFloat(abs(sin(t * 2 * .pi / 1.15))) * 3)
                }
            } else {
                canvas(broom: sweeping || broom ? -4 : nil, bob: 0)
            }
        }
        .frame(width: width, height: pose.height(forWidth: width))
        .task(id: lively && !reduceMotion) {
            guard lively, !reduceMotion else { return }
            await live()
        }
    }

    private var reduceMotion: Bool { systemReduceMotion || still }

    private func canvas(broom: Double?, bob: CGFloat) -> some View {
        let g = gaze ?? .zero
        let look = DustyLook(eye: CGSize(width: g.width * 3.4, height: g.height * 2.8), blink: blink,
                             earL: earL, earR: earR, broom: broom, specks: specks, specksFly: specksFly, bob: bob)
        return DustyCanvas(pose: pose, look: look)
            .animation(.easeOut(duration: 0.14), value: g)
    }

    private func live() async {
        var nextTwitch = Date().addingTimeInterval(.random(in: 3.5...7))
        while !Task.isCancelled {
            try? await Task.sleep(nanoseconds: UInt64(Double.random(in: 2.6...6.2) * 1e9))
            if Task.isCancelled { return }
            await blinkOnce()
            if Double.random(in: 0...1) < 0.18 {
                try? await Task.sleep(nanoseconds: 140_000_000)
                await blinkOnce()
            }
            if Date() >= nextTwitch {
                nextTwitch = Date().addingTimeInterval(.random(in: 4.5...9.5))
                let right = Double.random(in: 0...1) < 0.7
                withAnimation(.spring(response: 0.16, dampingFraction: 0.5)) { if right { earR = 10 } else { earL = -7 } }
                try? await Task.sleep(nanoseconds: 170_000_000)
                withAnimation(.spring(response: 0.38, dampingFraction: 0.55)) { earR = 0; earL = 0 }
            }
        }
    }

    @MainActor private func blinkOnce() async {
        withAnimation(.easeIn(duration: 0.05)) { blink = 0.08 }
        try? await Task.sleep(nanoseconds: 110_000_000)
        withAnimation(.easeOut(duration: 0.08)) { blink = 1 }
    }
}

/// Dusty for an empty state: he pops up once when the state first appears.
struct DustyArrival: View {
    var pose: DustyPose
    var width: CGFloat
    @Environment(\.accessibilityReduceMotion) private var systemReduceMotion
    @Environment(\.dustyStill) private var still
    private var reduceMotion: Bool { systemReduceMotion || still }
    @State private var shown = false

    var body: some View {
        Dusty(pose: pose, width: width)
            .scaleEffect(shown || reduceMotion ? 1 : 0.86, anchor: .bottom)
            .opacity(shown || reduceMotion ? 1 : 0)
            .onAppear {
                guard !reduceMotion else { return }
                withAnimation(.spring(response: 0.42, dampingFraction: 0.62).delay(0.05)) { shown = true }
            }
            .accessibilityHidden(true)
    }
}
